apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: grafanas.integreatly.org
  annotations:
    helm.sh/hook: crd-install
  creationTimestamp: null
spec:
  group: integreatly.org
  names:
    kind: Grafana
    listKind: GrafanaList
    plural: grafanas
    singular: grafana
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  validation:
    openAPIV3Schema:
      required: ["spec"]
      type: object
      properties:
        spec:
          type: object
          properties:
            containers:
              type: array
              items:
                type: object
                description: Additional container to add to the grafana pod
            secrets:
              type: array
              items:
                type: string
                description: Secret to be mounted as volume into the grafana deployment
            configMaps:
              type: array
              items:
                type: string
                description: Config map to be mounted as volume into the grafana deployment
            initResources:
              type: object
              description: Describes init compute resource requirements
            resources:
              type: object
              description: Describes compute resource requirements
            logLevel:
              type: string
              description: Log level of the grafana instance, defaults to info
            adminUser:
              type: string
              description: Default admin user name
            adminPassword:
              type: string
              description: Default admin password
            basicAuth:
              type: boolean
              description: Basic auth enabled
            disableLoginForm:
              type: boolean
              description: Disable login form
            disableSignoutMenu:
              type: boolean
              description: Disable signout menu
            anonymous:
              type: boolean
              description: Anonymous auth enabled
            config:
              type: object
              description: Grafana config
            ingress:
              type: object
              properties:
                enabled:
                  type: boolean
                  description: Create an ingress / route
                path:
                  type: string
                  description: Ingress path
                hostname:
                  type: string
                  description: The hostname of the ingress / route
                annotations:
                  type: object
                  description: Additional annotations for the ingress / route
                labels:
                  type: object
                  description: Additional labels for the ingress / route
                targetPort:
                  type: string
                  description: Override port to target in the grafana service
                tlsEnabled:
                  type: boolean
                  description: Use tls for the ingress / route
                tlsSecretName:
                  type: string
                  description: Name of the ingress certificate secret
                termination:
                  type: string
                  description: Used in Openshift, dictates where the secure communication will stop
            service:
              type: object
              properties:
                ports:
                  type: array
                  description: Override default ports
                  items:
                    type: object
                    description: A port to add to the grafana service
                annotations:
                  type: object
                  description: Additional annotations for the service
                labels:
                  type: object
                  description: Additional labels for the service
                type:
                  type: string
                  description: Service type (NodePort, ClusterIP or LoadBalancer)
            deployment:
              type: object
              properties:
                annotations:
                  type: object
                  description: Additional annotations for the service
                labels:
                  type: object
                  description: Additional labels for the service
                replicas:
                  type: integer
                  description: Grafana replicas
                nodeSelector:
                  type: object
                  description: Additional labels for the running grafana pods in a labeled node
                tolerations:
                  type: array
                  description: Additonal labels for running grafana pods in tained nodes
                affinity:
                  type: object
                  description: Additonal labels for running grafana pods with affinity properties
                securityContext:
                  type: object
                  description: Pod security context
                containerSecurityContext:
                  type: object
                  description: Container security context
                terminationGracePeriodSeconds:
                  type: integer
                  description: Grafana termination grace period
            serviceAccount:
              type: object
              properties:
                annotations:
                  type: object
                  description: Additional annotations for the serviceaccount
                labels:
                  type: object
                  description: Additional labels for the serviceaccount
                imagePullSecrets:
                  type: array
                  description: Additional image pull secrets for the serviceaccount
            client:
              type: object
              description: Grafana client settings
            compat:
              type: object
              description: Backwards compatibility switches
            dashboardLabelSelectors:
              type: array
              items:
                type: object
                description: Label selector or match expressions
            dashboardNamespaceSelector:
              type: object
              description: Namespace selector for dashboards
            dataStorage:
              type: object
              properties:
                annotations:
                  type: object
                  description: Additional annotations for the data storage
                labels:
                  type: object
                  description: Additional labels for the data storage
                accessModes:
                  type: array
                  items:
                    type: string
                    description: Persistent volume access mode
                size:
                  type: string
                  description: Size of persistent volume
                class:
                  type: string
                  description: Persistent volume storage class
            jsonnet:
              type: object
              description: Jsonnet library configuration
            baseImage:
              type: string
              description: Override base image
