{{- if .Values.additionalConfigmaps }}
apiVersion: v1
kind: List
items:
{{- range .Values.additionalConfigmaps }}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: {{ .name }}
    labels:
      {{- include "grafana-operator.labels" $ | nindent 6 }}
  data:
    {{- toYaml .data | nindent 4 }}
{{- end }}
{{- end }}
