{{- if .Values.grafanaDataSource }}
apiVersion: v1
kind: List
items:
{{- range .Values.grafanaDataSource }}
- apiVersion: integreatly.org/v1alpha1
  kind: GrafanaDataSource
  metadata:
    name: {{ .name }}
    labels:
      {{- include "grafana-operator.labels" $ | nindent 6 }}
  spec:
    name: {{ .name }}.yaml
    datasources:
      - name: {{ .datasourceName }}
        type: {{ .type }}
        access: {{ .access }}
      {{- if .urlTemplated }}
        url: {{ tpl (.url) $ }}
      {{- else }}
        url: {{ .url | quote }}
      {{- end }}
      {{- if .orgId }}
        orgId: {{ .orgId }}
      {{- end }}
      {{- if .uid }}
        uid: {{ .uid }}
      {{- end }}
      {{- if .database }}
        database: {{ .database | quote }}
      {{- end }}
      {{- if .user }}
        user: {{ .user | quote }}
      {{- end }}
      {{- if .basicAuth }}
        basicAuth: {{ .basicAuth }}
      {{- end }}
      {{- if .basicAuthUser }}
        basicAuthUser: {{ .basicAuthUser | quote }}
      {{- end }}
      {{- if .withCredentials }}
        withCredentials: {{ .withCredentials }}
      {{- end }}
      {{- if .secureJsonData }}
        {{- with .secureJsonData }}
        secureJsonData:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- end }}
      {{- if .jsonData }}
        {{- with .jsonData }}
        jsonData:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- end }}
        isDefault: {{ .isDefault }}
        version: {{ .version }}
        editable: {{ .editable }}
{{- end }}
{{- end }}
