{{- if .Values.grafana }}
apiVersion: v1
kind: List
items:
{{- range .Values.grafana }}
- apiVersion: integreatly.org/v1alpha1
  kind: Grafana
  metadata:
    name: {{ .name }}
    labels:
      app: {{ template "grafana-operator.name" $ }}
      chart: {{ template "grafana-operator.chart" $ }}
      release: {{ $.Release.Name }}
  spec:
    {{- if .containers }}
    containers:
    {{- range .containers }}
    - {{ . }}
    {{- end }}
    {{- end }}
    {{- if .secrets }}
    secrets:
    {{- range .secrets }}
    - {{ . }}
    {{- end }}
    {{- end }}
    {{- if .configMaps }}
    configMaps:
    {{- range .configMaps }}
    - {{ . }}
    {{- end }}
    {{- end }}
    {{- with .initResources }}
    initResources:
      {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .resources }}
    resources:
      {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- if .logLevel }}
    logLevel: {{ .logLevel }}
    {{- end }}
    {{- if .adminUser }}
    adminUser: {{ .adminUser }}
    {{- end }}
    {{- if .adminPassword }}
    adminPassword: {{ .adminPassword }}
    {{- end }}
    basicAuth: {{ .basicAuth }}
    disableLoginForm: {{ .disableLoginForm }}
    disableSignoutMenu: {{ .disableSignoutMenu }}
    anonymous: {{ .anonymous }}
    ingress:
      enabled: {{ .ingress.enabled }}
      {{- if .ingress.path }}
      {{- if .ingress.pathTemplated }}
      path: "{{ tpl (.ingress.path) $ }}"
      {{- else }}
      path: "{{ .ingress.path }}"
      {{- end }}
      {{- end }}
      {{- if .ingress.hostname }}
      {{- if .ingress.hostnameTemplated }}
      hostname: "{{ tpl (.ingress.hostname) $ }}"
      {{- else }}
      hostname: "{{ .ingress.hostname }}"
      {{- end }}
      {{- end }}
      {{- with .ingress.annotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .ingress.labels }}
      labels:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .ingress.targetPort }}
      targetPort: {{ .ingress.targetPort }}
      {{- end }}
      tlsEnabled: {{ .ingress.tlsEnabled }}
      {{- if .ingress.tlsSecretName }}
      tlsSecretName: {{ .ingress.tlsSecretName }}
      {{- end }}
      {{- if .ingress.termination }}
      termination: {{ .ingress.termination }}
      {{- end }}
    {{- if .service.enabled }}
    service:
    {{- with .service.ports }}
      ports:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .service.annotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .service.labels }}
      labels:
        {{ toYaml . | nindent 8 }}
    {{- end }}
      type: {{ .service.type }}
    {{- end }}
    {{- with .client }}
    client:
      {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .compat }}
    compat:
      {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- if or .serviceAccount.annotations .serviceAccount.labels }}
    serviceAccount:
      {{- with .serviceAccount.annotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .serviceAccount.labels }}
      labels:
        {{ toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    config:
    {{- if .configTemplated }}
      {{ tpl (toYaml .config) $ | nindent 6 }}
    {{- else }}
      {{ toYaml .config | nindent 6 }}
    {{- end }}
    {{- if .dashboardLabelSelector }}
    dashboardLabelSelector:
      {{ toYaml .dashboardLabelSelector | nindent 6 }}
    {{- end }}
    {{- with .dashboardNamespaceSelector }}
    dashboardNamespaceSelector:
      {{ toYaml . | nindent 6 }}
    {{- end }}
    deployment:
      replicas: {{ .deployment.replicas }}
    {{- if .deployment.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .deployment.terminationGracePeriodSeconds }}
    {{- end }}
    {{- with .deployment.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .deployment.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .deployment.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- if .deployment.securityContext }}
    {{- with .deployment.securityContext }}
      securityContext:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- if .deployment.containerSecurityContext }}
    {{- with .deployment.containerSecurityContext }}
      containerSecurityContext:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- if .dataStorage.enabled }}
    dataStorage:
    {{- with .dataStorage.annotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .dataStorage.labels }}
      labels:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .dataStorage.accessModes }}
      accessModes:
        {{ toYaml . | nindent 8 }}
    {{- end }}
      size: {{ .dataStorage.size }}
      class: {{ .dataStorage.class }}
    {{- end }}
{{- end }}
{{- end }}