{{- if .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "grafana-operator.serviceAccountName" . }}
  labels:
    app: {{ template "grafana-operator.name" . }}
    chart: {{ template "grafana-operator.chart" . }}
    release: {{ .Release.Name }}
  {{- if .Values.operator.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.operator.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}