{{- if .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "grafana-operator.serviceAccountName" . }}
  labels:
    {{- include "grafana-operator.labels" . | nindent 4 }}
  {{- if .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.operator.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
